import type { NextPage } from "next"
import Head from "next/head"
import footer from "../../../parts/footer"
import styles from "../../../styles/Home.module.css"

import useSWR from "swr"
import axios from "axios"
import { useState } from "react"

const RoomsPage: NextPage = () => {
  const fetcher = (url: string) => axios(url).then((response) => response.data)
  const { data, error } = useSWR<Room[]>("/api/rooms", fetcher)

  const [room, setRoom] = useState<Room | undefined>()

  return (
    <div className={styles.container}>
      <Head>
        <title>Rooms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Rooms</h1>

        {room === undefined ? (
          <div className={`${styles.grid} ${styles.column}`}>
            {data &&
              data.map((room: Room) => (
                <a
                  key={room.id}
                  className={styles.card}
                  href="#"
                  onClick={() => setRoom(room)}
                >
                  <h2>{room.data.name} &rarr;</h2>
                  <p>{room.data.comment}</p>
                </a>
              ))}
          </div>
        ) : (
          <div className={`${styles.grid} ${styles.column}`}>
            <a
              className={styles.card}
              href="#"
              onClick={() => setRoom(undefined)}
            >
              <h2>&larr; Back</h2>
              <p>to list of rooms</p>
            </a>
            <p className={styles.code}>
              ID: {room.id}
              <br />
              <br />
              Owner: {room.data.owner}
              <br />
              <br />
              Name: {room.data.name}
              <br />
              <br />
              Comment: {room.data.comment}
            </p>
          </div>
        )}

        <div className={styles.grid}>
          <a className={styles.card} href="/dashboard">
            <h2>Dashboard</h2>
            <p>Go back to dashboard</p>
          </a>
          <a className={styles.card} href="/auth/logout">
            <h2>Log out</h2>
            <p>Quit your session</p>
          </a>
        </div>
      </main>

      {footer}
    </div>
  )
}

export default RoomsPage
