import type { NextPage } from "next"
import Head from "next/head"
import footer from "src/parts/footer"
import styles from "styles/Home.module.css"

import useSWR from "swr"
import axios from "axios"
import { useState } from "react"
import { DashboardCard, LogoutCard } from "src/parts/cards"

const RoomListSkeleton = () => {
  return <>Room list is loading...</>
}

const RoomsPage: NextPage = () => {
  const fetcher = (url: string) => axios(url).then((response) => response.data)
  const { data, error } = useSWR("/api/rooms", fetcher)

  const [room, setRoom] = useState<Room | undefined>()

  return (
    <div className={styles.container}>
      <Head>
        <title>Rooms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Rooms</h1>
        <pre>{JSON.stringify(data)}</pre>

        {room === undefined ? (
          <div className={`${styles.grid} ${styles.column}`}>
            {/* {data === undefined ? (
              <RoomListSkeleton />
            ) : data.length === 0 ? (
              <>You have no rooms</>
            ) : (
              data.map((room: Room) => (
                <a
                  key={room.id}
                  className={styles.card}
                  href="#"
                  onClick={() => setRoom(room)}
                >
                  <h2>{room.data.name} &rarr;</h2>
                  <p>{room.data.comment}</p>
                </a>
              ))
            )} */}
          </div>
        ) : (
          <div className={`${styles.grid} ${styles.column}`}>
            <a
              className={styles.card}
              href="#"
              onClick={() => setRoom(undefined)}
            >
              <h2>&larr; Back</h2>
              <p>to list of rooms</p>
            </a>
            <p className={styles.code}>
              ID: {room.id}
              <br />
              <br />
              Owner: {room.data.owner}
              <br />
              <br />
              Name: {room.data.name}
              <br />
              <br />
              Comment: {room.data.comment}
            </p>
          </div>
        )}

        <div className={styles.grid}>
          <DashboardCard />
          <LogoutCard />
        </div>
      </main>

      {footer}
    </div>
  )
}

export default RoomsPage
