import type { NextPage } from "next"
import Head from "next/head"
import footer from "src/parts/footer"
import styles from "styles/Home.module.css"

import axios from "axios"
import { createRef, useContext, useState } from "react"
import { GlobalContext } from "src/contexts"
import {
  HomepageCard,
  LoginConfirmCard,
  LogoutCard,
  RegisterCard,
} from "src/parts/cards"
import { useRevalidateAuth } from "src/use"

const LoginPage: NextPage = () => {
  const revalidateAuth = useRevalidateAuth()
  const global = useContext(GlobalContext)
  const [error, setError] = useState<string | undefined>(undefined)

  const email = createRef<HTMLInputElement>()
  const password = createRef<HTMLInputElement>()

  const fetcher = (url: string, params?: object) =>
    axios.post(url, params).then((response) => response.data)

  const login = async () => {
    if (email.current === null) return setError("Email input is missing")
    if (password.current === null) return setError("Password input is missing")
    if (email.current.value.length === 0)
      return setError("Email input is empty")
    if (password.current.value.length === 0)
      return setError("Password input is empty")

    const params = {
      email: email.current.value,
      password: password.current.value,
    }

    const { data, error } = await fetcher("/api/auth/login", params)

    if (error !== undefined) setError(`${error.name}: ${error.code}`)
    else {
      setError("Login: success")
      console.log("LOGON", data)
    }

    // revalidateAuth()
  }

  const errorBlock = (
    <span className={`${styles.code} ${error !== undefined && styles.error}`}>
      {error !== undefined ? (
        error
      ) : global.isAuthenticated ? (
        <>You are logged in</>
      ) : (
        <>status...</>
      )}
    </span>
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Login form</h1>
        {errorBlock}

        <p className={styles.description}>
          E-mail:
          <br />
          <input
            className={styles.code}
            disabled={global.isAuthenticated}
            ref={email}
          />
          <br />
          <br />
          Password:
          <br />
          <input
            className={styles.code}
            disabled={global.isAuthenticated}
            ref={password}
          />
        </p>

        <div className={styles.grid}>
          <LoginConfirmCard onClick={login} />
          <RegisterCard />
          <HomepageCard />
          <LogoutCard />
        </div>
      </main>

      {footer}
    </div>
  )
}

export default LoginPage
