import axios from "axios"
import type { NextPage } from "next"
import Head from "next/head"
import { useEffect, useState } from "react"
import footer from "../../parts/footer"
import styles from "../../styles/Home.module.css"
import { AUTH_LOGOUT } from "../../src/enum"
import { Card } from "../../src/components"
import { AUTH_STATUS } from "../../src/enum"
import { useAuthStatus } from "../../src/use"

const { AUTH } = AUTH_STATUS
const { SUCCESS, NOAUTH, ERROR } = AUTH_LOGOUT

const LoginPage: NextPage = () => {
  const status = useAuthStatus()
  const [error, setError] = useState<string | undefined>(undefined)

  useEffect(() => {
    if (status === AUTH_STATUS.NOAUTH) setError("You are not logged in")
  }, [status])

  const logout = async () => {
    const { data } = await axios.get("/api/auth/logout")
    const result =
      data === SUCCESS
        ? "success"
        : data === NOAUTH
        ? "you were not logged in"
        : data === ERROR
        ? "error occured"
        : "UNKOWN"

    setError("Logout: " + result)
    console.log(data)
  }

  const errorBlock = (
    <span className={`${styles.code} ${error !== undefined && styles.error}`}>
      {error || <>status...</>}
    </span>
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Logout form</h1>
        {errorBlock}

        <div className={styles.grid}>
          <Card
            header="Confirm logout &rarr;"
            paragraph="Log out and clear sessions"
            onClick={logout}
            disabled={status === NOAUTH}
          />
          <Card header="Home page" paragraph="Go back to home page" link="/" />
          <Card
            header="Dashboard"
            paragraph="All Cryptotech tools in one place"
            link="/dashboard"
            disabled={status !== AUTH}
          />
        </div>
      </main>

      {footer}
    </div>
  )
}

export default LoginPage
