import axios from "axios"
import type { NextPage } from "next"
import Head from "next/head"

import footer from "src/parts/footer"
import styles from "styles/Home.module.css"
import { useErrorReporter } from "src/use"
import {
  DashboardCard,
  HomepageCard,
  LoginCard,
  LogoutConfirmCard,
} from "src/parts/cards"
import { useContext, useEffect } from "react"
import { GlobalContext } from "src/contexts"

const LogoutPage: NextPage = () => {
  const global = useContext(GlobalContext)
  const [error, setError, errorBlock] = useErrorReporter()

  const logout = async () => {
    const { data, error } = await axios
      .post("/api/auth/logout", {
        session: global.session,
      })
      .then((response) => response.data)

    if (error !== undefined) setError(error)
    else {
      setError("success")
      global.setSession(undefined)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Logout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Logout form</h1>
        <>{errorBlock}</>

        <div className={styles.grid}>
          <LogoutConfirmCard onClick={logout} />
          <LoginCard />
          <HomepageCard />
          <DashboardCard />
        </div>
      </main>

      {footer}
    </div>
  )
}

export default LogoutPage
