import type { NextPage } from "next"
import Head from "next/head"
import { useState } from "react"
import footer from "../../parts/footer"
import styles from "../../styles/Home.module.css"

import axios from "axios"

const RegisterPage: NextPage = () => {
  const [error, setError] = useState<string | undefined>(undefined)

  const fetcher = (url: string, params?: object) =>
    axios.post(url, params).then((response) => response.data)

  const register = async () => {
    const params = {
      email: "lol",
      password: "pass",
    }

    const { data, error } = await fetcher("/api/auth/register", params)

    if (error !== undefined) setError(`${error.name}: ${error.code}`)
    else {
      setError("Login: success")
      console.log("REGISTERED", data)
    }
  }

  const errorBlock = (
    <span className={`${styles.code} ${error !== undefined && styles.error}`}>
      {error || <>status...</>}
    </span>
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Registration form</h1>
        {errorBlock}

        <p className={styles.description}>
          E-mail:
          <br />
          <input className={styles.code} />
          <br />
          <br />
          Password:
          <br />
          <input className={styles.code} />
        </p>

        <div className={styles.grid}>
          <a className={styles.card} href="#" onClick={register}>
            <h2>Go &rarr;</h2>
            <p>
              Enter <b>credentials above</b> and click here to continue to{" "}
              <b>Cryptotech CRM</b>.
            </p>
          </a>
          <a className={styles.card} href="/auth/login">
            <h2>Login</h2>
            <p>
              If you <b>already have an account</b> or have a social account
              attached
            </p>
          </a>
          <a className={styles.card} href="/">
            <h2>Home page</h2>
            <p>Go back to home page</p>
          </a>
        </div>
      </main>

      {footer}
    </div>
  )
}

export default RegisterPage
