import type { NextPage } from "next"
import Head from "next/head"
import { useContext, useState } from "react"
import footer from "src/parts/footer"
import styles from "styles/Home.module.css"

import axios from "axios"
import { Card } from "src/components"
import GlobalContext from "src/contexts/global"
import { HomepageCard, LoginCard, LogoutCard, RegisterConfirmCard } from "src/parts/cards"

const RegisterPage: NextPage = () => {
  const global = useContext(GlobalContext)
  const [error, setError] = useState<string | undefined>(undefined)

  const fetcher = (url: string, params?: object) =>
    axios.post(url, params).then((response) => response.data)

  const register = async () => {
    const params = {
      email: "lol",
      password: "pass",
    }

    const { data, error } = await fetcher("/api/auth/register", params)

    if (error !== undefined) setError(`${error.name}: ${error.code}`)
    else {
      setError("Login: success")
      console.log("REGISTERED", data)
    }
  }

  const errorBlock = (
    <span className={`${styles.code} ${error !== undefined && styles.error}`}>
      {error || global.isAuthenticated ? (
        <>You are logged in</>
      ) : (
        <>status...</>
      )}
    </span>
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Registration form</h1>
        {errorBlock}

        <p className={styles.description}>
          E-mail:
          <br />
          <input className={styles.code} />
          <br />
          <br />
          Password:
          <br />
          <input className={styles.code} />
        </p>

        <div className={styles.grid}>
          <RegisterConfirmCard onClick={register} />
          <LoginCard />
          <LogoutCard />
          <HomepageCard />
        </div>
      </main>

      {footer}
    </div>
  )
}

export default RegisterPage
