import type { NextPage } from "next"
import Head from "next/head"
import footer from "../parts/footer"
import styles from "../styles/Home.module.css"

const DashboardPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cryptotech CRM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://cryptotech.ee">Cryptotech</a> CRM
        </h1>

        <div className={styles.grid}>
          <a className={styles.card} href="/rooms">
            <h2>Rooms</h2>
            <p>Check status of all rooms.</p>
          </a>
          <a className={styles.card} href="/logout">
            <h2>Log out</h2>
            <p>Quit your session</p>
          </a>
          <a className={styles.card} href="/">
            <h2>Home page</h2>
            <p>Go back to home page</p>
          </a>
        </div>
      </main>

      {footer}
    </div>
  )
}

export default DashboardPage
