import type { NextPage } from "next"
import Head from "next/head"
import footer from "../parts/footer"
import { Card } from "../src/components"
import { useAuthStatus } from "../src/use"
import styles from "../styles/Home.module.css"
import { AUTH_STATUS } from "../src/enum"

const { AUTH } = AUTH_STATUS

const HomePage: NextPage = () => {
  const status = useAuthStatus()

  return (
    <div className={styles.container}>
      <Head>
        <title>Cryptotech CRM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://cryptotech.ee">Cryptotech</a> CRM
        </h1>

        <p className={styles.description}>
          Get started by <span className={styles.code}>authenticating()</span>{" "}
          first.
        </p>

        <div className={styles.grid}>
          <Card
            header="Login"
            paragraph={
              <>
                If you <b>already have an account</b> or have a social account
                attached
              </>
            }
            link="/auth/login"
            disabled={status === AUTH}
          />
          <Card
            header="Register"
            paragraph={
              <>
                In order to access <b>Cryptotech CRM</b> you need to create an
                account first.
              </>
            }
            link="/auth/register"
            disabled={status === AUTH}
          />
          <Card
            header="Dashboard"
            paragraph="All Cryptotech tools in one place"
            link="/dashboard"
            disabled={status !== AUTH}
          />
          <Card
            header="Log out"
            paragraph="Log out and clear all sessions"
            link="/auth/logout"
            disabled={status !== AUTH}
          />
        </div>
      </main>

      {footer}
    </div>
  )
}

export default HomePage
