import type { NextPage } from "next"
import Head from "next/head"
import footer from "src/parts/footer"
import styles from "styles/Home.module.css"
import {
  DashboardCard,
  LoginCard,
  LogoutCard,
  RegisterCard,
} from "src/parts/cards"

const HomePage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cryptotech CRM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://cryptotech.ee">Cryptotech</a> CRM
        </h1>

        <p className={styles.description}>
          Get started by <span className={styles.code}>authenticating()</span>{" "}
          first.
        </p>

        <div className={styles.grid}>
          <LoginCard />
          <RegisterCard />
          <DashboardCard />
          <LogoutCard />
        </div>
      </main>

      {footer}
    </div>
  )
}

export default HomePage
