import type { NextPage } from "next"
import Head from "next/head"
import footer from "../parts/footer"
import styles from "../styles/Home.module.css"

const LoginPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Login form</h1>

        <p className={styles.description}>
          Username:
          <br />
          <input className={styles.code} />
          <br />
          <br />
          Password:
          <br />
          <input className={styles.code} />
        </p>

        <div className={styles.grid}>
          <a className={styles.card} href="#">
            <h2>Go &rarr;</h2>
            <p>Enter <b>credentials above</b> and click here to continue to <b>Cryptotech CRM</b>.</p>
          </a>
          <a className={styles.card} href="/register">
            <h2>Register</h2>
            <p>In order to access <b>Cryptotech CRM</b> you need to create an account first.</p>
          </a>
          <a className={styles.card} href="/">
            <h2>Home page</h2>
            <p>Go back to home page</p>
          </a>
        </div>
      </main>

      {footer}
    </div>
  )
}

export default LoginPage
