import type { NextPage } from "next"
import Head from "next/head"
import footer from "../parts/footer"
import styles from "../styles/Home.module.css"

const LoginPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Logout form</h1>

        <p className={`${styles.code} ${styles.error}`}>Currently inactive</p>

        <div className={styles.grid}>
          <a className={styles.card} href="/">
            <h2>Home page</h2>
            <p>Go back to home page</p>
          </a>
          <a className={styles.card} href="/dashboard">
            <h2>Dashboard</h2>
            <p>All Cryptotech tools in one place</p>
          </a>
        </div>
      </main>

      {footer}
    </div>
  )
}

export default LoginPage
