import type { NextPage } from "next"
import Head from "next/head"
import footer from "../parts/footer"
import styles from "../styles/Home.module.css"

const RegisterPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Registration form</h1>

        <p className={styles.description}>
          Username:
          <br />
          <input className={styles.code} />
          <br />
          <br />
          Password:
          <br />
          <input className={styles.code} />
        </p>

        <div className={styles.grid}>
          <a className={styles.card} href="#">
            <h2>Go &rarr;</h2>
            <p>
              Enter <b>credentials above</b> and click here to continue to{" "}
              <b>Cryptotech CRM</b>.
            </p>
          </a>
          <a className={styles.card} href="/login">
            <h2>Login</h2>
            <p>
              If you <b>already have an account</b> or have a social account
              attached
            </p>
          </a>
          <a className={styles.card} href="/">
            <h2>Home page</h2>
            <p>Go back to home page</p>
          </a>
        </div>
      </main>

      {footer}
    </div>
  )
}

export default RegisterPage
