import type { NextPage } from "next"
import Head from "next/head"
import footer from "../../parts/footer"
import { Card } from "../../src/components"
import { AUTH_STATUS } from "../../src/enum"
import { useAuthStatus } from "../../src/use"
import styles from "../../styles/Home.module.css"

const { AUTH } = AUTH_STATUS

const DashboardPage: NextPage = () => {
  const status = useAuthStatus()

  return (
    <div className={styles.container}>
      <Head>
        <title>Cryptotech CRM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://cryptotech.ee">Cryptotech</a> CRM
        </h1>

        <div className={styles.grid}>
          <Card
            header="Rooms"
            paragraph="Check status of all rooms."
            link="/dashboard/rooms"
            disabled={status !== AUTH}
          />
          <Card
            header="Log out"
            paragraph="Quit your session"
            link="/auth/logout"
            disabled={status !== AUTH}
          />
          <Card
            header="Home page"
            paragraph="Go back to home page"
            link="/"
            disabled={false}
          />
        </div>
      </main>

      {footer}
    </div>
  )
}

export default DashboardPage
